### ISSUE TITLE
[Code Release]: In this week

### ISSUE THREAD

**Issue by SCNU-RISLAB** [Li-Qingyun/RSCoTr#1] opened 2024-11-05 16:57 UTC

**Comment by Li-Qingyun** [comment] 2024-11-06 02:02
忘了🤡，这两天弄一下

**Comment by Leafdoctor** [comment] 2024-11-06 02:43
6个月之前的soon

**Comment by Li-Qingyun** [comment] 2024-11-06 02:52
> 6个月之前的soon

🤥确实，开完题过暑假打游戏打多了

立个flag这周

**Comment by ld-xy** [comment] 2024-11-06 03:35
> > 6个月之前的soon
> 
> 🤥确实，开完题过暑假打游戏打多了
> 
> 立个flag这周

好好好，中国人不骗中国人！！！！！

**Comment by Li-Qingyun** [comment] 2024-11-06 03:46
**I apologize for the delay in submitting the RSCoTr code, caused by distractions from graduation project preparations, new paper submission, gaming, and pet caring. I am committed to completing the code's open-sourcing this week and will continue to maintain the repository. I’d be delighted if RSCoTr can be helpful to anyone. Please feel free to reach out if you’d like to discuss anything—I truly hope it can contribute to future work.**

**Closed by Li-Qingyun** 2024-11-06 03:46 UTC
